on:
  workflow_dispatch:
    inputs:
      ref:
        description: Reference (commit, branch, tag, ...)
        default: stable
      dry_run:
        description: Perform dry run (just print file diffs and don't commit)
        type: boolean
        default: false


jobs:
  dxpy:
    name: Build dxpy and release it to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.10'

      - name: Build dxpy
        run: python3 setup.py sdist
        working-directory: src/python

      - name: Deploy dist package
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: dxpy-src
          path: src/python/dist/*.tar.gz

  dxpy-deb-xenial:
    name: Build dxpy Debian package for Ubuntu 16.04
    runs-on: ubuntu-latest
    steps:
      - name: Build debian package
        run: |
          mkdir dist
          docker run -v ./dist:/out --rm dnanexus/dx-toolkit:16.04 \\
            /bin/bash -xc \"git clone https://github.com/dnanexus/dx-toolkit.git; \\
            cd dx-toolkit; git checkout ${{ github.event.inputs.ref }}; build/build-dx-toolkit-debs.sh; \\
            mv /*.{changes,deb,dsc,tar.xz} /out/\"
      - name: Deploy dist package
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: dxpy-deb-xenial
          path: dist/*