on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
      dry_run:
        description: Perform dry run (just print file diffs and don't commit)
        type: boolean
        default: false

jobs:
  prepare:
    name: Prepare for build
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y devscripts
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.10'

      - name: Verify changelog
        run: |
          grep -F "`echo ${{ github.event.inputs.version }} | cut -d. -f2-`" CHANGELOG.md

      - name: Bump dxpy version
        run: echo "version = '${{ github.event.inputs.version }}'" > src/python/dxpy/toolkit_version.py

      - name: Bump dxR version
        run: sed -i -e 's/[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.event.inputs.version }}/g' src/R/dxR/DESCRIPTION src/R/dxR/R/dxR-package.R src/R/dxR/man/dxR-package.Rd

      - name: Prepare debian package changelog
        run: python3 build/convert_changelog.py -v "${{ github.event.inputs.version }}" -a "Kurt Jensen" -e "kjensen@dnanexus.com" CHANGELOG.md

      - name: Prepare API wrappers
        run: make -C ./src api_wrappers

      - name: Ensure all expected files were changed
        run: |
          if git diff --exit-code src/python/dxpy/toolkit_version.py src/R/dxR/DESCRIPTION src/R/dxR/R/dxR-package.R src/R/dxR/man/dxR-package.Rd > /dev/null; then
            exit 1
          else
            exit 0
          fi

      - name: Print diff
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: git diff

      - name: Commit and push changes
        if: ${{ github.event.inputs.dry_run == 'false' }}
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a